### ISSUE TITLE
Morning session peer review 

### ISSUE THREAD

**Issue by AbdusSattar-70** [ritikarawat220/To-Do-list#9]
### Highlight
✔️ Followed JavaScript best practices
✔️ Followed DRY, KISS, and YAGNI rules.
✔️ Followed HTML and CSS best practices
✔️ Followed No linter errors
✔️ Followed Used GitHub Flow
✔️ Followed Work documented professionally.
**suggestion****optional **

- [x] It would be better to add the `Install` parameter In your readme.MD file so anyone will understand how they install it on their local machine.

**Comment by ritikarawat220** [comment]
**@AbdusSattar-70**  

<img src="https://media4.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif"/>

_I have updated README.md file and added the INSTALL parameter... 💯_
